= Service Provisioning Implementation

== Problem

Crossplane brings a lot of lifecycle features for XRDs and XRs.
While developing the https://github.com/vshn/appcat-service-prototype[service prototype] it became apparent that some functionality is missing in Crossplane out-of-the-box.

=== Missing Features In Crossplane 1.6

[qanda]
Generate random strings::
See discussions in https://github.com/crossplane/crossplane/issues/1895[#1895] and https://github.com/crossplane/crossplane/pull/2308[#2308].
Currently the https://github.com/mittwald/kubernetes-secret-generator[Secret generator] is used but this should be regarded as a workaround.

Webhook support for validations and custom business logic::
See design proposal in https://github.com/crossplane/crossplane/pull/2719[#2719].

Delay reconciliations to specific times when using `CompositionRevisions` feature::
This is needed to enable maintenance windows.

Cross-resource references within `Composition`::
This could eliminate a lot of patch duplications.
See discussions in https://github.com/crossplane/crossplane/issues/1770[#1770] and https://github.com/crossplane/crossplane/issues/2099[#2099].

[NOTE]
====
This list doesn't mean that they should be part of Crossplane, only that they are missing from the PoV of AppCatalog.
====

=== Deployment Requirements

There are several additional resources required along the usual deployment resources.

[qanda]
Base service runtime::
* Helm release
* Crossplane resources for cloud instances

Backup::
* S3 Buckets (through Crossplane)
* K8up `Schedule`

Service Monitoring::
* Prometheus `ServiceMonitor`
* Prometheus `PrometheusRule`

Networking::
* `NetworkPolicy` to allow traffic to the service.

RBAC::
* `RoleBinding` to grant read access for requesting customer to instance logs.

Customer association::
Each instance needs to be associated to the requesting customer for billing the services.
This might require additional business logic.

== Proposals

=== Proposal 1: Umbrella Charts

The primary deployment strategy will be a Helm chart that contains most, if not all deployment artifacts.
This includes cloud instances provisioned by Crossplane itself.

Additional logic is implemented through custom webhooks and controllers.

.Service provisioning with an umbrella Helm chart
image::appcat_proposal_1.drawio.svg[]

The "umbrella" chart contain all the feature gates and dependent charts required to provision services on the supported cloud infrastructure.
The chart takes input parameters such as

- cloud provider
- major version
- backup enabled
- SLA (alerting enabled)

and then deploys the resources as required.

The chart is also used when cloud instances are provisioned.
For example, there may be additional Prometheus exporters needed in case the cloud instance doesn't provide Prometheus metrics endpoints.

In addition to the composition, there are webhooks to perform validations and assignment to customer.
Also, a dedicated version update controller delays changing of `CompositionRevisions` to the newest version until a specific time is met.

Advantages::
- Umbrella chart is able to deploy arbitrary resources
- Umbrella chart is integration testable

Disadvantages::
- Separate version controller required for automated updates.
- Webhook controller required (possibly per service).
- Logic and feature gates in umbrella chart is limited by Helm's templating engine.

=== Proposal 2: Side Charts

The main difference to proposal 1 is that the umbrella chart is split up into parts where just the service is deployed and another where the additional resources are deployed.

It is assumed that the additional resources are roughly the same for all services, thus they are packaged into one side chart.

.Service provisioning with a common "side" Helm chart
image::appcat_proposal_2.drawio.svg[]

If the service is a cloud instance, instead of deploying the service chart, the Crossplane resource is used.

In addition to the composition, there are webhooks to perform validations and assignment to customer.
Also, a dedicated version update controller delays changing of `CompositionRevisions` to the newest version until a specific time is met.

Advantages::
- Easier onboarding of new services.
- Side chart is able to deploy arbitrary resources.

Disadvantages::
- It assumes that every service requires roughly the same common resources that can be packed into one chart.
- Webhook controller required (possibly per service).
- Logic and feature gates in side chart is limited by Helm's templating engine.
- Side chart and service definition are loosely coupled.

=== Proposal 3: Dedicated Provider

This proposal uses a dedicated Crossplane provider to deploy and configure all the resources that the service needs.
A Crossplane provider uses code thus provides the most flexibility.

.Service provisioning with a dedicated Crossplane provider
image::appcat_proposal_3.drawio.svg[]

Advantages::
- Flexible deployment using code and Kubernetes API.
- Webhook controller can be built-in.
- Built-in version update controller.
- Strong coupling of the resources.
- Generating the resources is unit testable.

Disadvantages::
- There may be a lot of code repetition between services that deploy the same set of common resources.
- Impact of versioning mechanics of a provider is currently unknown.

=== Proposal 4: Sub Providers

This proposal is similar to proposal 3, however it uses dedicated Crossplane providers for each sub component.
A Crossplane provider uses code thus provides the most flexibility.

.Service provisioning with multiple Crossplane providers
image::appcat_proposal_4.drawio.svg[]

Advantages::
- Flexible deployment using code and Kubernetes API.
- Webhook controller can be built-in.
- Built-in version update controller.
- Generating the resources is unit testable.

Disadvantages::
- Loose coupling of the resources.
- A lot of repetition in the compositions.
- Impact of versioning mechanics of a provider is currently unknown.

=== Proposal 5: Dedicated Provider With Side Chart

This proposal combines the ideas of proposal 3 with proposal 2.
A Crossplane provider uses code to provision the service, whereas the additional resources are deployed using a Helm chart.

.Service provisioning with a dedicated Crossplane provider and side chart
image::appcat_proposal_5.drawio.svg[]

Advantages::
- Flexible deployment using code and Kubernetes API.
- Webhook controller can be built-in.
- Built-in version update controller.
- Generating the resources is unit testable.
- Common resources are sharable between services using the chart.

Disadvantages::
- Loose coupling between service and additional resources.
- Impact of versioning mechanics of a provider is currently unknown.
- Logic and feature gates in side chart is limited by Helm's templating engine.

=== Proposal 6: Free Choice

This proposal does not impose a certain strategy how services are to be provisioned.
Each service can choose how to best provision the required resources in a `Composition`.

Custom webhooks and version update controller would still be required.

Advantages::
- Flexible deployment strategy

Disadvantages::
- No common ground between services makes maintenance and day-2 operations difficult.

== Decision

Proposal 3: Dedicated Provider

== Rationale

Dedicated providers bring the most flexibility.
They are in code and thus easier testable and other business code is easily integrated.
Crossplane already provides templates and development guides to create new providers, so most boilerplate code should be available.
