= MongoDB

== Problem

We want to Provide MongoDB via AppCat.
But their licensing might be an issue.
This decision looks closely at the licensing and alternative products that can be used as drop-in replacements for MongoDB.

== Proposals

Proposal 1: Use MongoDB Community Edition::
MongoDB community edition is licensed under the https://github.com/mongodb/mongo/blob/master/LICENSE-Community.txt[SSPL].
The SSPL dictates that the source code for the tooling that provides the services, needs to be available to the public as well.
However, it would also need to be licensed under the SSPL.

Proposal 2: Use MongoDB Enterprise Operator::
MongoDB Enterprise Operator can be used to manage MongoDB instances on Kubernetes.
There have already been preliminary contact with MongoDB about the licensing for our use with AppCat.
However, these documents are at the time of writing internally.
There's a https://github.com/mongodb/helm-charts/tree/main/charts/enterprise-operator[helm chart] to deploy it.
It does need an https://www.mongodb.com/pricing[enterprise license] though.
Which will require a license key to be present on the K8s clusters.

Proposal 3: Use FerreDB with PostgreSQL::
https://www.ferretdb.com/[FerretDB] is a Drop-In replacement.
FerretDB is an adaptor for PostgreSQL which exposes a MongoDB compatible API.
It uses PostgreSQL as the backend to store data.
FerretDB itself is stateless and can be deployed as deployments alongside a PostgreSQL instance.
However, it does not implement everything that https://docs.ferretdb.io/diff/[MondoDB supports].
So a MongoDB AppCat service based on FerretDB might not be fully compatible with all workloads, which can result in bad UX for the customers.

== Decision
Use MongoDB Enterprise Operator.

This is the only viable option to run a MongoDB SaaS on K8s.
There's no helm based deployment for MongoDB Enterprise Edition.

== Rationale
Either licensing or compatibility prevent us from using any of the other mentioned solutions.
