= ADR 0037 - MariaDB Bitnami Replacement
:adr_author:    Nicolas Bigler
:adr_owner:     Schedar
:adr_reviewers: 
:adr_date:      2025-07-30
:adr_upd_date:  2025-07-30
:adr_status:    draft
:adr_tags:      mariadb,bitnami,helm,service

include::partial$adr-meta.adoc[]

[NOTE]
.Summary
====
Short and concise summary of the decision in this ADR.
====

== Problem

For our VSHNMariaDB offering we relied on the Bitnami helm chart. However, the https://github.com/bitnami/containers/issues/83267[announced changes to the Bitnami catalog] forces us to re-evaluate our options.

== Evaluated options

[cols="1,1,1,1,1,1,1"]
|===
| Name | Type | Galera Support | Recovery support | Active project? | Metrics | Notes
| Bitnami | Helm chart | ✅ | ✅ (Manually) | ✅ | ✅ (as a sidecar per mariadb pod)| Very expensive (~50'000$/year)
| Mariadb-operator | Operator | ✅ | ✅ (Fully automated via operator) | ✅ | ✅ | Very active project with very frequent releases
| Codership/Galera | Helm chart | ✅ | ✅ (Manually) | ✅ Not much happing on the repo at the moment. Last release was ~6 months ago. | ❌ | It's designed for use with mysql rather then MariaDB. Documentation is limited.
|===

== Comparison

=== Mariadb-operator

The mariadb-operator is an excellent operator that fully supports galera including automated recovery from a cluster failure.
It's the official operator by the MariadDB developers and is under heavy development with lots of updates regularely.
Maintenance is as easy as changing the version tag.
The operator also provides CRs for Backup and Restore. You can do a restore to an existing instance or bootstrap a new instance and provide the backed up data as source for the bootstrap.
Backup and restore can be done to a PVC or to an S3 backend.

It's not possible to have metrics for every pod at the moment, as the mysqld-exporter is deployed as a separate deployment rather than as a sidecar to the individual pods. Therefore the metrics visiblity is limited to specific pod / cluster level metrics.


=== Bitnami

We have used the bitnami charts for running MariaDB/Galera for a while now.
They are well tested and accepted in the community. However, there are some caveats:
No automated recovery: The helm chart is static and doesn't provide any logic during the runtime and therefore can't provide any active recovery mechanisms. A cluster needs to be manually bootstrapped in case of a cluster failure.

It also doesn't provide a backup and restore solution. This needs to be implemented and handled by the end user.

Last but not least, the versioned image tags are not freely accessible anymore after 2025-08-28 and require an expensive subscription to have access to specific tags of the images.


== Decision

The Mariadb-Operator is the most promising solution for us right now for the following reasons:

* Official solution from MariaDB itself
* Under active and heavy development
* Automated cluster recovery support
* Integrated backup and restore support
* Open-source and free to use.


== Consequences

With the decision to migrate away from Bitnami to the Mariadb-Operator, we need to refactor the MariaDB service in our Appcat and SPKS offering. Also a migration path for existinging instances needs to be properly evaluated and implemented. This is rather time consuming. However, it's still justified as the price for the bitnami images is too high.
