= ADR 0039 - Servala Framework Requirements
:adr_author:    Tobias Brunner
:adr_owner:     Schedar
:adr_reviewers: Schedar
:adr_date:      2025-09-30
:adr_upd_date:  2025-09-30
:adr_status:    draft
:adr_tags:      framework

include::partial$adr-meta.adoc[]

[NOTE]
.Summary
====
This ADR specifies the requirements for the Servala Framework.
====

== Vision

> Transform a Kubernetes workload into a standardized managed service - “Helm Chart in - Managed Service out”

(Substitute Helm Chart with “any Kubernetes artifact.”)

The Servala framework (also called the AppCat framework) allows to easily add day-2 operations facilities to any cloud-native application and offer it through Servala as a self-service SaaS application.

Day-2 operations means:

* Regular Maintenance and security fixes
* Version Upgrades
* Backup and Restore
* Monitoring and Alert handling
* Metrics and Logging

In adherence to the xref:framework/service-maturity.adoc[Service Maturity levels].

== Scope

The framework targets already built OCI compliant container images.
Building of these container images is outside of the scope of the Servala framework.

== Personas and User Stories

This section outlines personas which are users of the framework and their user stories.

=== Services Engineer

The services engineers creates a managed service by using the Servala framework and makes the service available in the self-service portal.
They are the experts in the services which is beeing SaaSified.

_As a services engineer, I want to_:

* add day-2 operations to the service I'm expert in
* make the service available in the self-service portal
* give the end-user of the service parameters to customize the service behaviour
* be able to easily add a new service

=== Framework Engineer

The framework engineer develops the framework tooling and the tools required to make day-2 operations possible.

_As a framework engineer, I want to_:

* provide the services engineer an easy to use framework to build managed services
* have a rock-solid base which others can rely on
* be able to easily develop the framework
* sleep well because the testing infrastructure has all the requirements covered

=== Self-Service Portal

The self-service portal consumes the catalog of managed services built by using the Servala framework.

_As a self-service portal, I want to_:

* connect to an API to get a list of available services
* retrieve the available parameters of a service to provide the user a form
* be sure that there is a standard I can rely to

== Core Requirements

Kubernetes API::
The framework and the control-plane is based on the Kubernetes API.
This is the core technology used at VSHN and has the most experience around.
Moving away from the Kubernetes API as the core architecture would be a significant change with plenty of risks involved.

Core Tooling::
The framework will rely on many tooling, assuming this tooling is available and ready to use.
This core tooling must be mostly industry standard, so that compatibility is given.
Examples: Prometheus for metrics collection.

Independence::
The framework must be independent of VSHN Managed Kubernetes and VSHN Managed OpenShift.
This mainly means it must not depend on Project Syn to allow deploying the service catalog to non-VSHN managed Kubernetes environments.

Open Source::
All tooling developed and used must be open source.

Automation::
The focus lies on automation, including keeping software up-to-date.
