= Glossary

== General

=== Service
An application that can be ordered.
It is automatically provisioned, can be consumed by a service consumer and generally adheres to our quality requirements.

=== Service Consumer
An application that connects to a service instance as a client.

=== Service Order
The act of deploying a Kubernetes resource that triggers the provisioning of a new service instance.

=== Service Instance
A single isolated ocurrurance of a service.

==== Cloud Instance
An instance of a cloud service offering by a cloud service provider.

==== Converged Service Instance
An instance of a converged service blueprint.
Either in the same namespace as the service order was made or in another namespace.

== Service Location

Services can be provisioned on various places:

=== Converged Cluster
Service instance runs on the same cluster as the service consumer.

=== Service Cluster
Service runs on one or more dedicated clusters, reserved for services.

=== Cloud Service
A type of service architecture offered by a cloud service provider such as AWS or GCP.

=== Converged Service
A type of service developed to run on a converged cluster.

==== Converged Service Architectures
Architecture refers to the deployment strategy of a service instance in relation to high availability.

Standalone::
A single node instance without any high availability.

Replicated::
The service offers data replication to one or more other instances.

Clustered::
A fully clustered version of the service, usually offering active / active replication with fully automated cluster handling.

== Personas

=== Service User
A human that interacts with {product}.

=== Service Maintainer
A human that engineers and maintains a service (code).

=== Service Engineer
A human that performs day-2 operations or resolves incidents.
