= Usability

== Provisioning of a Service Happens Fully Automated

Source::
User

Stimulus::
Orders a service via the provided APIs.

Environment::
AppCatalog enabled Kubernetes cluster

Artifact::
`kubectl` or equivalent tool

Response::
Service ready (status condition)

Response measure::
Service ready depending on service architecture in normal conditions:
- Standalone: within 10 minutes
- Replicated: within 20 minutes
- Clustered: within 30 minutes
- Cloud instance: within 20 minutes

Rationale::
The user can work with the instance in an acceptable time frame.

[NOTE]
====
- The provided APIs can vary according to the environment.
- The service is provisioned asynchronously and its readiness status has to be polled regularly.
====

== Day-2 Operations of a Service Are Well-Defined and Automated as Far as Possible

Source::
Engineer

Stimulus::
Resolve an open alert from a given AppCatalog Service instance.

Environment::
Monitoring and Alerting

Artifact::
Alerting software

Response::
The alert details include a Runbook URL.

Response measure::
The Runbook URL links to the service documentation that contains specific recommendations or instructions how to resolve the given alert.

Rationale::
Each alert should be actionable for the on-call engineer.

== Each Service Enforces Contraints

Source::
User

Stimulus::
Provision an AppCatalog Service instance with an invalid spec.

Environment::
AppCatalog enabled Kubernetes cluster

Artifact::
`kubectl` or equivalent tool

Response::
The provisioning of the service instance fails with an message containing the reason why the provisioning fails.

Response measure::
The provisioning is aborted.

Rationale::
Services with excessive resource usage or special configurations aren't commercially reasonable.
Each service must document and enforce constraints that limit the resources and impact of abnormal conditions so that the user cannot use it out of certain boundaries.

== All Service Logs Are Accessible

Source::
User

Stimulus::
Views the service's logs

Environment::
APPUiO Cloud

Artifact::
`kubectl`

Response::
All logs of the service are visible.

Response measure::
The service's logs can be viewed via kubectl.

Rationale::
To give the users more flexibility with debugging issues and using the services, we will provide access to the service's logs.

[NOTE]
====
Currently only available for APPUiO Cloud for Helm-based services.
====

== Configuration of Services Is a Declarative Approach
Source::
User

Stimulus::
Changes the manifest of an AppCatalog service

Environment::
AppCatalog enabled Kubernetes cluster

Artifact::
`kubectl` or equivalent tool

Response::
Service instance configuration is changed according to desired state.

Response measure::
Observed service instance state is updated in the manifest.

Rationale::
Service instance provisioning (complete stack) should be as user-friendly as deploying a custom application in Kubernetes with GitOps in mind.
This gives users a native Kubernetes experience.
