= Maintainability

== Service Production Readiness Standards

Source::
Product Owner

Stimulus::
Approve service production readiness (new and changing services)

Environment::
AppCatalog enabled Kubernetes cluster

Artifact::
// Placeholder for now. Future "Service Hub" docs?
https://kb.vshn.ch[VSHN Documentation]

Response::
Documentation and specification of all services adhere to a common standard.

Response measure::
Each service documentation contains at least the following structure:
- Metrics and alerts
- SLIs
- Runbooks
- Tutorial (Getting started)
- How-to guides
- Backup and restore reference
- API reference
- Operational constraints

Rationale::
Each service must adhere to a checklist for production readiness.
The documentation shall be consistent across all services.

////
Note for future "best practices"
- We should lower the operational load by using good Kubernetes health checks
- In a shared cloud environment, it is crucial to secure the services, so no other people have access to it (TLS + auth)
- Provide connection details Secret in the app namespace
- Service API shall not use plaintext secrets (use Secret reference instead)
////
