= Reliability

== Backup of Data Is Conducted at Least Every 24h

Source::
Service engineer

Stimulus::
Inspect backups

Environment::
AppCatalog enabled Kubernetes cluster

Artifact::
Backup tool

Response::
List of available backups.

Response measure::
Consecutive backups don't exceed the 24h interval.

Rationale::
At least one backup per day is the accepted norm for backups.
Services may define shorter intervals.

== Services Are Kept Up-To-Date with Automatic Updates

Source::
User

Stimulus::
Uses an AppCatalog Service

Environment::
AppCatalog enabled Kubernetes cluster

Artifact::
Crossplane and Helm

Response::
Approved updates are rolled out to running services automatically in the next maintenance window.

Response measure::
Affected services are up-to-date with the approved version after the user-provided maintenance window.

Rationale::
- Up-to-date services generally contain bugfixes and security patches that improve the service's reliability.
  It is in the interest of service engineers and users that they stay secure.
- Users shall have the option to choose the maintenance window.

== Mandatory Updates Are Rolled Out to All Services

Source::
Service engineer

Stimulus::
Desire to roll out mandatory updates to all service instances.

Environment::
AppCatalog enabled Kubernetes cluster

Artifact::
tbd

Response::
Mandatory updates are rolled out immediately.

Response measure::
Affected services are up-to-date with the mandatory update.

Rationale::
Service engineers need to be able to roll out mandatory updates to all instances, regardless of their configured maintenance window.
This allows for special kinds of updates, such as critical security patches.

[NOTE]
====
Ideally mandatory updates are announced beforehand.
====
