= Portability

== Services Run Independent of the Cloud They Are Provisioned
Source::
User

Stimulus::
Creates an AppCatalog Service

Environment::
AppCatalog enabled Kubernetes cluster

Artifact::
Kubectl or Service Broker API

Response::
The services are provisioned the same way for any cluster.

Response measure::
The usage for provisioning services is transparent for any underlying Kubernetes distribution.
The same API calls and CRs can be used to provision AppCatalog services.

Rationale::
`kubectl` and equivalent tools shall provide the common means for interacting with the AppCatalog framework.
In general it doesn't matter where the platform is running on, although there may be cloud provider specific APIs.

== Backups Can Be Exported

Source::
Service engineer

Stimulus::
Export an existing backup

Environment::
AppCatalog enabled Kubernetes cluster

Artifact::
K8up and restic

Response::
The backup is in a format that can be exported.

Response measure::
The backup data can be inspected and used to fully restore a service instance outside of AppCat with conventional tools.

Rationale::
Vendor lock-in users into the service instances or AppCat framework must be avoided.
The users should be able to take their data away before canceling their service instances.
