= Service Requirements and Iterations

Implementing and maintaining a service is iterative work.
The idea is to release early and release often, without having the urge to have all features available right from the beginning.

This page gives an idea on the iterative steps.
Except the initial version and the feature complete version, all steps in-between can be in any order, as it fits best.
With "feature complete" it's not meant that the service doesn't receive new functionality or doesn't get maintained anymore, we're talking about the default scope outlined on this page.

Important is that every step is independent of each other. A service that implements `Abigor` doesn't necessarily already implement `Melchom `.
That in turn also means we must allow some leeway for each service in respect to the requirements, should a service not allow for a feature or makes it overly complex.
A service is allowed to deviate from a requirement when it makes sense and can be documented and reasoned about accordingly.

To understand the personas referenced in this document, see xref:reference/glossary.adoc#_personas[Glossary - Personas].

== Initial Release "Alpha"

As a user of the service I can:

* create a service instance
* update the configuration of a service instance
* delete a service instance

See also:

* xref:reference/quality-requirements/usability/api-declarative.adoc[Declarative Configuration of Instances]
* xref:reference/quality-requirements/usability/api-validation.adoc[Service Instance API Validation]
* xref:reference/quality-requirements/usability/provisioning-time.adoc[Provisioning Time]

== Iteration "Bathin"

As a user of the service I can:

* enable Backup on a service instance
* disable Backup on a service instance
* manually restore data for a service instance

See also:

* xref:reference/quality-requirements/portability/backup-exports.adoc[Backups Can Be Exported]
* xref:reference/quality-requirements/reliability/backup-interval.adoc[Minimum Backup Interval]

== Iteration "Settulco"

As a user of the service I can:

* access logs of a service instance

See also:

* xref:reference/quality-requirements/usability/logs.adoc[Service Instance Logs]

== Iteration "Melchom"

As a user of the service I can:

* see metrics of a service instance
* access a dashboard showing pre-crafted diagrams

== Iteration "Abigor"

As a user of the service I can:

* enable alerting on pre-defined SLIs to VSHN so that VSHN can resolve incidents with priority
* see SLO reports so that I can get an overview of how well my instance performs

As an engineer of the service I can:

* access operations runbooks so that I can resolve upcoming alerts

See also:

* xref:reference/quality-requirements/usability/actionable-alerts.adoc[Actionable Alerts]

== Iteration "Marbas"

As a user of the service I can:

* enable regular maintenance on a service instance

== Iteration "Dantalion"

As a user of the service I can:

* upgrade the service instance version

== Stable Release

As a user of the service I can:

* rely on production readiness of the service

All requirements from xref:reference/quality-requirements/maintainability/readiness-standards.adoc[Service Production Readiness Standards] are met.
