= Setup HTTP _Basic_ authentication

This how-to will explain how a _Service Catalog_ is connected to a _Crossplane Service Broker_ using HTTP _Basic_ authentication.

== Preparations

- xref:app-catalog:ROOT:how-tos/crossplane_service_broker/setup_crossplane_service_broker.adoc[Have a _Crossplane Service Broker_ in your cluster] that's configured for HTTP _Basic_ authentication and know the configured _username_ and the _password_.
- xref:app-catalog:ROOT:how-tos/crossplane_service_broker/setup_service_catalog.adoc[Have a _Service Catalog_ running on your cluster.]
- https://svc-cat.io/docs/install/#installing-the-service-catalog-cli[Have `svcat` installed on your computer.]

[TIP]
=====
If you are planing on using the _Crossplane Service Broker_ in a multi-tenant environment, then we strongly recommend to consider implementing xref:app-catalog:ROOT:how-tos/crossplane_service_broker/bearer_token_authentication.adoc[HTTP _Bearer Token_ authentication] instead of HTTP _Basic_ authentication.
=====

== Configuring HTTP _Basic_ authentication
// tag::main[]

To configure _Basic_ authentication, first create a secret that contains the username and the password.
Then register the _Crossplane Service Broker_ through the basic authentication mechanism:

```bash
# Create a new secret containing the Basic authentication secrets
kubectl create secret generic basic-creds --from-literal=username=test --from-literal=password=changeMeEventually

# Unregister the Crossplane Service Broker if you already registered it previously
svcat unregister servicebroker-test

# Register the Crossplane Service Broker using the Basic authentication secret
svcat register servicebroker-test --basic-secret basic-creds --url "http://service-broker-test.service-broker"

# Check the Crossplane Service Broker's status
svcat get brokers
```
// end::main[]
