= Change AppCat service quota on APPUiO Cloud

It's important, that the service instance has been created with resources lower than the quota.
This is due to the fact, that the quotas are bound to the namespace and in order to change them, we need the namespace itself.

== Namespace quotas
The amount of namespaces and thus the amount of AppCat instances that can be created for an organization on APPUiO is limited by default. Please see the https://github.com/appuio/component-appuio-cloud/blob/master/class/defaults.yml#L174[component defaults] for the actual default number.

If that limit is reached, the customer can request an increase in the amount of namespaces they can have.
Please see https://kb.vshn.ch/appuio-cloud/how-to/day2ops/override-namespace-quota.html[Override Namespace Quota].

== Resource quotas
The resource quotas are controlled by annotations on the instance namespaces.
AppCat adjusts the default values slightly, so that `plus-8` or `standard-8` instances could run with one replica.

To adjust the quotas, simply adjust the values of the annotations:

[source,yaml]
----
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    resourcequota.appuio.io/organization-compute.limits.cpu: 4500m
    resourcequota.appuio.io/organization-compute.limits.memory: 16500Mi
    resourcequota.appuio.io/organization-compute.requests.cpu: 4500m
    resourcequota.appuio.io/organization-compute.requests.memory: 16500Mi
    resourcequota.appuio.io/organization-objects.requests.storage: "1099511627776"
----
