= Web Portal

image::portal-webapp-arch.drawio.svg[]

The Web Portal provides the multi-tenant multi-service-provider aggregation and central entry-point.
All access to the Meta VSHN Application Marketplace happens through this control plane.
It offers features needed to separate organizations, control access, service provisioning and gives a central view over multi cloud providers and the instances running this way.
It's built as a classic web application in the sense of a "monolith", consuming various third party APIs to provide an aggregated and opinionated view.

It's crucial to know where an organization is coming from, because that dictates various important aspects like what services are available, how billing works and more.
For this we track the origin of an organization in a new field on the `Organization` resource called `.spec.originRef` and configure the origin-specific aspects in `OrganizationOriginConfig`.

== Terminology

We Portal (Portal)::
This is the aggregated view and entry point for the user.
It provides the mechanisms for the multi-tenant, multi-service-provider self-service portal.

CSP Control Plane (CSPCP)::
This runs Crossplane and the AppCat Control Plane which manages all the service instances on worker clusters.
Each zone of a CSP runs at least one CSPCP.

Worker Cluster::
Clusters running the actual workload, managed by the CSPCP.
Each zone of a CSP runs at least one Worker Cluster.
Services are directly exposed to the end-user.

Service::
A managed service which can be instantiated (ordered) and parametrized according to the specification.

Plan::
A pre-defined set of parameters for a service.

Crossplane specific terms::
* Compositions - A template to define how to create resources.
* Composite Resource Definition (`XRD`) - A custom API specification.
* Composite Resource (`XR`) - Created by using the custom API defined in a Composite Resource Definition. XRs use the Composition template to create new managed resources.
* Claims (`XRC`) - Like a Composite Resource, but with namespace scoping.
* Managed Resource (`MR`) - Represents an external service in a Provider.
* Providers enable Crossplane to provision infrastructure on an external service. Providers create new Kubernetes APIs and map them to external APIs.

== Struggles

Main idea: Move all the multi-tenant, multi-cloud-service logic into the Portal.
The Crossplane Control Planes main job is the deploy and manage service instances.
The Portal manages access to the CSPCPs and creates the service instances there.

=== Reuse APPUiO stuff or not

Should we reuse the APPUiO specific assets for Organizations, Teams, Users, BillingEntities and Invitations?

We could create Organizations etc. directly from the Web Application in the APPUiO Control API.
We could also just do these things directly in the web application.

For billing purposes, we'd need to link between Organization, BillingEntity and the actual service deployed.

If we have Organizations in the Portal, we'd track the origin in there.
We could then have the Organization configuration including CSPCP and service filtering directly in the web app.

=== Service catalog

How should we present the service catalog and expose the configuration fields?
We could query the Compositions / XRDs and dynamically expose the fields, or hardcode the service catalog to begin with and to make it easier at the beginning.

How about editing a service when the fields are hardcoded? We'd need to query the CSPCP and map the response to the hardcoded fields.
Reuse the service spec from the Go code structs somehow?

If not hardcoded, how to map the API spec to the fields then?

For the organization origin, we filter the available CSPCPs and if coming from OSB API, filter the enabled services.

=== Source of truth

Service definitions must be on the CSPCP and must not be stored in the Portal DB.
The source of truth is always at the CSPCP, so that these control planes are independent of the Portal.

Namespaces are labeled with the organization names.
We filter on label selectors and RBAC on the Portal.
The portal connects with the users credential to the CSPCP (Token Exchange).

The portal makes sure the RBAC is configured when creating namespaces.
Creation of namespaces happens with a more privileged service account.

=== Billing

Simplify billing somehow? Depending on how services are billed. -> Leave that to Odoo.

=== Initial onboarding

How do we onboard a user coming from Exoscale?





== Service Provisioning

The Portal crafts the Kubernetes Object and directly applies it to the corresponding CSPCP.
No state is stored in the Portal, it's always directly fetched from the CSPCP.

We need graceful degradation should one CSPCP for whatever reason not be available.

=== Connection Secrets

Secrets are exposed in the Portal, but ony when clicking on it (hidden by default).

=== Dynamic Data

There is some dynamic data on the CSPCPs which needs to be made available on the CCP.
For example the backup listing is fully dynamic.

=== Organization Namespace on CSPCP

An Organization namespace is required on each CSPCP where a service is provisioned, to place the Claim into it.
