= CI/CD Processes
:page-aliases: reference/ci-cd.adoc

AppCat contains many repositories.
They all converge in the `component-appcat`, which is responsible for deploying everything.

In order to streamline our development process, we improved the CI/CD with following steps:

* Creating a PR in an AppCat repository automatically builds images and packages
* Creating a PR in an AppCat repository automatically creates a PR on the component that reflects the changes, so it can instantly be deployed any SYN cluster to test
* Proper labels on the PRs are enforced
* Merging a PR will automatically create a release, according to the labels it will detect what version increment it needs to do
* The auto release is not active on the component repository

== How to manage the CI/CD pipelines

All the files that specify the process are managed via cruft and cookiecutter.
The repository is: https://github.com/vshn/appcat-cookiecutter.
Each of the AppCat repos contains a cronjob that checks for changes every 60 minutes.
If there are changes it will open a new PR.

== Automated AppCat CI

There are automated workflows in place in AppCat repository that should streamline our development between AppCat and Component repositories.

IMPORTANT: Color purple shows user action

=== Releases from AppCat

The release has to be manually dispatched, usually before the end of the sprint, on Tuesday.
The following is the lifecycle of the release process:

image::release.svg[Release Diagram]

=== Automated Feature Requests from AppCat

All feature requests starting from AppCat repository have the following lifecycle:

image::feature-request.svg[Feature Request Diagram]

=== Automated Hotfix from AppCat

All hotfixes requests starting from AppCat repository have the following lifecycle:

image::hotfix.svg[Hotfix Diagram]