= Cloud Based AppCat Services
:page-aliases: reference/cloud-usage-reporting.adoc

This page explains how cloud based services handle usage reporting.

== Data Flow Overview

image::cloud-based-billing-flow.svg[Cloud]

The usage reporting process involves two main steps, where data is gathered, processed, and transferred to Odoo:

. The https://github.com/vshn/billing-collector-cloudservices/[Billing Collector for Cloud Services] is an application that gathers, processes, and transfers data.
. Data is then transferred to Odoo.

== Billing Collector for Cloud Services

The billing collector for cloud services collects data from Cloudscale and Exoscale providers. It gathers Object Storage and DBaaS usage data from the respective cloud providers.

From https://www.cloudscale.ch/[Cloudscale], we collect Object Storage usage data.
From https://www.exoscale.com/[Exoscale], we collect Object Storage and DBaaS usage data.

The default parameters for how often data is collected or transferred depend on the specific cloud provider.

=== Exoscale

The following default configuration applies to Exoscale:

[source,yaml]
----
billing:
  exoscale:
    enabled: false
    dbaas:
      enabled: false
      collectIntervalMinutes: 15 <1>
    objectStorage:
      enabled: false
      collectIntervalHours: 23 <2>
      billingHour: 6 <3>
----
<1> The DBaaS instances are checked every 15 minutes to see if they still exist.
<2> The Object Storage is checked daily for existence and general usage metrics.
<3> The time of day when Object Storage usage data is collected.

=== Cloudscale

The following default configuration applies to Cloudscale:

[source,yaml]
----
billing:
  cloudscale:
    enabled: false
    collectIntervalHours: 23 <1>
    billingHour: 6 <2>
    days: 1 <3>
----
<1> The Object Storage is checked daily for existence.
<2> The time of day when Object Storage usage data is collected.
<3> The number of days of historical usage data to collect.

NOTE: The complete configuration for both providers can be accessed in our https://github.com/vshn/component-appcat/blob/master/class/defaults.yml[component-appcat].

== Odoo Integration

Data is processed in Odoo via a https://central.vshn.ch/web#action=1172&model=queue_message.metered_usage&view_type=list&menu_id=587&cids=1[Job Queue]. Each job corresponds to a CronJob, and messages are either accepted or rejected.
If accepted, the data becomes accessible and filterable on the https://central.vshn.ch/web#action=1171&model=vshn.metered.usage&view_type=list&menu_id=216&cids=1[Sales] webpage.

NOTE: Some links may require permissions and might not be accessible if you do not have the necessary rights.

=== Data Model and Flow

Refer to the https://docs.central.vshn.ch/metered-billing-data-flow.html[Data Model and Flow] for a generic overview of how data flows into Odoo.
