= Framework 2.0 Features

Implementing and maintaining a service is iterative work.
The idea is to release early and release often, without having the urge to have all features available right from the beginning.

This page outlines the features that the Framework 2.0 provides for its services. The feature development is ongoing.
For each * xref:reference/application-catalog-docs/docs/modules/ROOT/pages/framework/framework-2-0/services.adoc[service] it is the responsibility of the respective * xref:reference/application-catalog-docs/docs/modules/ROOT/pages/framework/framework-2-0/personas/service-maintainer.adoc[service maintainer] to make the framework features available to the  * xref:reference/application-catalog-docs/docs/modules/ROOT/pages/framework/framework-2-0/personas/service-user.adoc[service user]. 

The available features for each service will be listed under https://products.docs.vshn.ch/products/appcat/services_index.html[VSHN Application Catalog^].

== Provisioning

As a service maintainer of AppCat 2.0 I can:

* define service provisioning
* propagate user changes
* ensure deprovisioning
* expose credentials and networking


== Backup

As a user of the service I can:

* provision buckets for backups
* get a default k8up backup, to be customized or disabled
* define service specific backup and restore operations

The backup includes e2e tests.

= Planned Framework 2.0 Features

== Restore

As a user of the service I can:

* manually restore data for a service instance

== Logs

As a user of the service I can:

* access logs of a service instance

== Metrics

As an engineer of the service I can:

* see the raw metrics of a service instance
* access a dashboard showing pre-crafted diagrams of the available metrics

As a user of the service I can:

* see the SLA reports

== Alerting

As a user of the service I can:

* enable alerting on pre-defined SLIs to VSHN so that VSHN can resolve incidents with priority
* enable alerting on the capacity of the instances to an alert channel of my choice so that I can prevent incidents

As an engineer of the service I can:

* access operations runbooks so that I can resolve issues

== Maintenance

As a user of the service I can:

* enable regular maintenance on a service instance

== Version Upgrade

As a user of the service I can:

* upgrade the service instance version

== Scaling

As a user of the service I can:

* adjust the size of the service (provision replicas/instances)

== User Management

As a user of the service I can:

* manage roles, grants and databases

== Billing

As a user of the service I can:

* automatically receive service bills
